### ISSUE TITLE
E (17435) gpio: gpio_install_isr_service(460): GPIO isr service already installed

### ISSUE THREAD

**Issue by e135193** [lemariva/uPyCam#20]
I have flashed the latest firmware however the module restarts itself with the error below @lemariva

```
connecting to network...
network config: ('192.168.0.26', '255.255.255.0', '192.168.0.1', 'X.X.X.X')
E (17435) gpio: gpio_install_isr_service(460): GPIO isr service already installed
MicroPython v1.14-122-g9fef1c0bd-dirty on 2021-03-30; Camera Module (i2s) with ESP32
Type "help()" for more information.
```

and when I run main.py I get error below

```
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "webserver.py", line 48, in run
OSError: Camera Init Failed
```

**Comment by sogrekci** [comment]
I have same error also..

**Comment by jvsteiner** [comment]
hmm.  I get this too - any clues?
